- name: Print clipboard string
  debug:
    msg: "vless://{{ xray_uuid.stdout }}@{{ vless.domain }}:443?type=xhttp&security=reality&mode=auto&path=%2F{{ xhttp_path }}&pbk={{ x25519_pbk.stdout }}&fp=chrome&sni={{ vless.domain }}&sid={{ xray_sid }}#{{ xray_remark }}"
- name: XRay outbound config
  debug:
    msg: |
          {
            "tag": "default",
            "protocol": "vless",
            "settings": {
              "vnext": [
                {
                  "address": "{{ vless.domain }}",
                  "port": 443,
                  "users": [
                    {
                      "id": "{{ xray_uuid.stdout }}",
                      "encryption": "none"
                    }
                  ]
                }
              ]
            },
            "streamSettings": {
              "network": "xhttp",
              "security": "reality",
              "xhttpSettings": { "mode": "auto", "path": "/{{ xhttp_path }}" },
              "realitySettings": {
                "serverName": "{{ vless.domain }}",
                "fingerprint": "chrome",
                "publicKey": "{{ x25519_pbk.stdout }}",
                "shortId": "{{ xray_sid }}",
                "spiderX": "/"
              }
            }
          }
- name: Sing-box outbound config
  debug:
    msg: |
          {
              "type": "vless",
              "server": "{{ vless.domain }}",
              "server_port": 443,
              "uuid": "{{ xray_uuid.stdout }}",
              "tls": {
                  "enabled": true,
                  "server_name": "{{ vless.domain }}",
                  "utls": {
                      "enabled": true,
                      "fingerprint": "chrome"
                  },
                  "reality": {
                      "enabled": true,
                      "public_key": "{{ x25519_pbk.stdout }}",
                      "short_id": "{{ xray_sid }}"
                  }
              },
              "transport": {
                  "type": "xhttp",
                  "path": "/{{ xhttp_path }}",
                  "mode": "auto"
              }
          }
- name: Print PBK, SID and UUID to connect to server.
  debug:
    msg: "UUID: {{ xray_uuid.stdout }}, PBK: {{ x25519_pbk.stdout }}, SID: {{ xray_sid }}, Path: /{{ xhttp_path }}"
